### ISSUE TITLE
Feature request: Hide properties marked with `@private` (on non-private components)

### ISSUE THREAD

**Issue by adrianschmidt** [jgroth/kompendium#126]
We have a PR in lime-elements that adds a property to a publicly documented component, but we don't really want to advertise this property, as we may change it in the future, but we need it internally for now. As seen in the screenshot below, the property has been marked as private, and we do get a little flag about that neatly rendered, and that's nice. But I'm think it would perhaps be better to just hide the documentation of that property completely?

<img width="1439" alt="image" src="https://github.com/jgroth/kompendium/assets/154725/1a6746a6-9e7b-4031-835d-7b8ebcb89df5">

**Comment by jgroth** [comment]
We should probably use `@internal` over `@private` since it's part of the TSDoc specification
https://tsdoc.org/pages/tags/internal/

**Comment by adrianschmidt** [comment]
Ah! It seems like `@internal` already works for properties 👍

**Comment by jgroth** [comment]
Aha! Great! I did not know that :smile:

**Comment by adrianschmidt** [comment]
If you use @internal for the whole component, it seems to get left out of the docs completely, not just excluded from the menu. So I think `@private` is useful on components, since we usually probably do want to be able to get to the docs, while `@internal` is useful if we really do want to properly exclude the docs too…
