### ISSUE TITLE
Sometimes tabs aren't opened by default when a page is loaded, you need to click them manually

### ISSUE THREAD

**Issue by Kiarokh** [jgroth/kompendium#23]
![image](https://user-images.githubusercontent.com/35954987/95072039-e223da80-070a-11eb-8482-7b2badf2ee3e.png)

**Comment by adrianschmidt** [comment]
I assume this is some kind of timing issue. Could be pretty difficult to track down. I've seen it too, but do we know if it ever happens in the published docs, or only when serving the local dev-build? If it doesn't happen in published docs, I don't think this is worth spending much time on… 🤔

**Comment by Kiarokh** [comment]
It has been a long time since I saw them on the published docs. So we maybe can close it for now.

**Comment by jgroth** [comment]
I don't think I have seen this, let's close it for now :slightly_smiling_face:
