### ISSUE TITLE
clicking outside the nav menu should close it in mobile

### ISSUE THREAD

**Issue by Kiarokh** [jgroth/kompendium#29]
On mobile, when you open the side-bar to navigate to another page, somehow it feels more natural to just click outside of it to close it. Currently user has to click the close button.

**Comment by jgroth** [comment]
I was testing some stuff on mobile just a few minutes ago and had a similar thought! However, I was thinking that the menu should close automatically when you click on an item :slightly_smiling_face:

**Comment by Kiarokh** [comment]
:D cool ;)

> menu should close automatically 

that may become annoying if you don't exactly know which page you wanna see and simply are surfing the content. (?) But may also work just fine. I don't really know which one is the best.

**Comment by jgroth** [comment]
You would have to close the menu anyway in order to know if you are on the correct page :smile:

**Comment by Kiarokh** [comment]
that's right 😅
