### ISSUE TITLE
The description for types gets wrapped half as wide as it should

### ISSUE THREAD

**Issue by adrianschmidt** [jgroth/kompendium#89]
<img width="1439" alt="Screenshot showing that the description text for types gets wrapped at half the width of the available space" src="https://user-images.githubusercontent.com/154725/179966053-5d4a2893-f605-40b3-b88a-791563b3a93a.png">

I suspect there might be a conflict with how things are shown in the _Components_ section… 🤔

**Comment by adrianschmidt** [comment]
@Kiarokh Perhaps you'd like to take a look at this one?

**Comment by Kiarokh** [comment]
⚡
